"""empty message

Revision ID: 17a62a5a63bb
Revises: 440539ad7715
Create Date: 2014-04-14 19:59:35.064823

"""

# revision identifiers, used by Alembic.
revision = '17a62a5a63bb'
down_revision = '440539ad7715'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('draft', sa.Column('body', sa.UnicodeText(), nullable=True))
    op.drop_column('draft', 'text')
    op.drop_column('draft', 'modifiers')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('draft', sa.Column('modifiers', sa.TEXT(), nullable=True))
    op.add_column('draft', sa.Column('text', sa.TEXT(), nullable=True))
    op.drop_column('draft', 'body')
    ### end Alembic commands ###
