"""empty message

Revision ID: 17e7e1170a96
Revises: 45ba0db89a30
Create Date: 2014-04-27 14:42:13.404973

"""

# revision identifiers, used by Alembic.
revision = '17e7e1170a96'
down_revision = '45ba0db89a30'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
