"""empty message

Revision ID: 1e7bb99c6862
Revises: 7ee09347107
Create Date: 2014-04-15 19:23:06.627604

"""

# revision identifiers, used by Alembic.
revision = '1e7bb99c6862'
down_revision = '7ee09347107'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('long_template', sa.UnicodeText(), nullable=True))
    op.add_column('notification', sa.Column('short_template', sa.String(length=80), nullable=True))
    op.drop_column('notification', 'short_text')
    op.drop_column('notification', 'long_text')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('long_text', sa.TEXT(), nullable=True))
    op.add_column('notification', sa.Column('short_text', sa.VARCHAR(length=80), nullable=True))
    op.drop_column('notification', 'short_template')
    op.drop_column('notification', 'long_template')
    ### end Alembic commands ###
