"""empty message

Revision ID: 29e8ca56ebca
Revises: None
Create Date: 2014-03-08 16:21:02.708454

"""

# revision identifiers, used by Alembic.
revision = '29e8ca56ebca'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unsubscribe_token',
    sa.Column('utid', sa.Integer(), nullable=False),
    sa.Column('token', sa.UnicodeText(), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('sent_date', sa.DateTime(), nullable=True),
    sa.Column('email_type', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('utid'),
    sa.UniqueConstraint('token')
    )
    op.create_table('user',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('url_keyword', sa.String(length=80), nullable=True),
    sa.Column('first_name', sa.String(length=30), nullable=True),
    sa.Column('last_name', sa.String(length=30), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('may_email', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('signup_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('url_keyword')
    )
    op.create_table('email',
    sa.Column('eid', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('signup_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('eid'),
    sa.UniqueConstraint('email')
    )
    op.create_table('password_token',
    sa.Column('ptid', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=80), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('date_sent', sa.DateTime(), nullable=True),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['user.uid'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('ptid'),
    sa.UniqueConstraint('token')
    )
    op.create_table('upload',
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('mimetype', sa.String(length=80), nullable=True),
    sa.Column('filename', sa.String(length=100), nullable=True),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['user.uid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('upload_id')
    )
    op.create_table('essay',
    sa.Column('eid', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['user.uid'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['upload_id'], ['upload.upload_id'], ),
    sa.PrimaryKeyConstraint('eid')
    )
    op.create_table('draft',
    sa.Column('did', sa.Integer(), nullable=False),
    sa.Column('eid', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('text', sa.UnicodeText(), nullable=True),
    sa.Column('finalized', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['eid'], ['essay.eid'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['uid'], ['user.uid'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('did')
    )
    op.create_table('review',
    sa.Column('rid', sa.Integer(), nullable=False),
    sa.Column('did', sa.Integer(), nullable=False),
    sa.Column('urlhash', sa.String(length=80), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['did'], ['draft.did'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('rid'),
    sa.UniqueConstraint('urlhash')
    )
    op.create_table('snapshot',
    sa.Column('sid', sa.Integer(), nullable=False),
    sa.Column('did', sa.Integer(), nullable=False),
    sa.Column('eid', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('title', sa.UnicodeText(), nullable=True),
    sa.Column('text', sa.UnicodeText(), nullable=True),
    sa.Column('time_taken', sa.DateTime(), nullable=True),
    sa.Column('taken_automatically', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['did'], ['draft.did'], ),
    sa.ForeignKeyConstraint(['eid'], ['essay.eid'], ),
    sa.ForeignKeyConstraint(['uid'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('sid')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('snapshot')
    op.drop_table('review')
    op.drop_table('draft')
    op.drop_table('essay')
    op.drop_table('upload')
    op.drop_table('password_token')
    op.drop_table('email')
    op.drop_table('user')
    op.drop_table('unsubscribe_token')
    ### end Alembic commands ###
