"""empty message

Revision ID: 351e377302a2
Revises: 17e7e1170a96
Create Date: 2014-06-16 20:02:47.081332

"""

# revision identifiers, used by Alembic.
revision = '351e377302a2'
down_revision = '17e7e1170a96'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('essay', 'modified_date')
    op.drop_column('essay', 'created_date')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('essay', sa.Column('created_date', postgresql.TIMESTAMP(), nullable=True))
    op.add_column('essay', sa.Column('modified_date', postgresql.TIMESTAMP(), nullable=True))
    ### end Alembic commands ###
