"""empty message

Revision ID: 39e409021994
Revises: 1e7bb99c6862
Create Date: 2014-04-19 18:22:43.425972

"""

# revision identifiers, used by Alembic.
revision = '39e409021994'
down_revision = '1e7bb99c6862'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('draft', sa.Column('created_date', sa.DateTime(), nullable=True))
    op.add_column('draft', sa.Column('modified_date', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('draft', 'modified_date')
    op.drop_column('draft', 'created_date')
    ### end Alembic commands ###
