"""empty message

Revision ID: 557ed3db49af
Revises: 39e409021994
Create Date: 2014-04-19 19:00:49.073145

"""

# revision identifiers, used by Alembic.
revision = '557ed3db49af'
down_revision = '39e409021994'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('essay', 'modified_date')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('essay', sa.Column('modified_date', postgresql.TIMESTAMP(), nullable=True))
    ### end Alembic commands ###
