"""empty message

Revision ID: 7ee09347107
Revises: 440539ad7715
Create Date: 2014-04-15 18:32:22.669993

"""

# revision identifiers, used by Alembic.
revision = '7ee09347107'
down_revision = '17a62a5a63bb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('nid', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('from_uid', sa.Integer(), nullable=True),
    sa.Column('short_text', sa.String(length=80), nullable=True),
    sa.Column('url', sa.String(length=80), nullable=True),
    sa.Column('long_text', sa.UnicodeText(), nullable=True),
    sa.Column('seen', sa.Boolean(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['from_uid'], ['user.uid'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['uid'], ['user.uid'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('nid')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification')
    ### end Alembic commands ###
